"""empty message

Revision ID: 47e22cbde93c
Revises: 616f9f7fa3ad
Create Date: 2020-05-28 20:14:58.529554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e22cbde93c'
down_revision = '616f9f7fa3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'show_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('venue', 'show_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'show_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artist', 'show_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
